from pathlib import Path

import pytest

from dbt_platform_helper.providers.yaml_file import DuplicateKeysException
from dbt_platform_helper.providers.yaml_file import FileNotFoundException
from dbt_platform_helper.providers.yaml_file import InvalidYamlException
from dbt_platform_helper.providers.yaml_file import YamlFileProvider


def test_returns_valid_yaml(fs):
    test_path = "./test"
    fs.create_file(Path(test_path), contents="key: value")
    result = YamlFileProvider.load(test_path)
    assert result == {"key": "value"}


def test_returns_empty_dict_given_empty_yaml(fs):
    test_path = "./test"
    fs.create_file(Path(test_path), contents="")
    result = YamlFileProvider.load(test_path)
    assert result == {}


def test_raises_exception_if_invalid_yaml(fs):
    test_path = "./test"
    fs.create_file(Path(test_path), contents="{")
    with pytest.raises(InvalidYamlException):
        YamlFileProvider.load(test_path)


def test_raises_exception_if_duplicate_keys_in_yaml(fs):
    test_path = "./test"
    fs.create_file(Path(test_path), contents="key1: name\nkey2: name\nkey1: name")
    with pytest.raises(DuplicateKeysException):
        YamlFileProvider.load(test_path)


def test_raises_exception_if_path_doesnt_exist(fs):
    test_path = "./test"
    with pytest.raises(FileNotFoundException):
        YamlFileProvider.load(test_path)


def test_writes_with_correct_contents(fs):
    test_path = ".platform-helper-config-cache.yml"
    test_content = {
        "redis": {"date-retrieved": "09-02-02 10:35:48", "versions": ["7.1", "7.2"]},
        "opensearch": {"date-retrieved": "09-12-24 16:00:00", "versions": ["6.1", "6.2"]},
    }
    test_comment = "# [!] This file is autogenerated via the platform-helper. Do not edit.\n"
    expected_test_cache_file = """# [!] This file is autogenerated via the platform-helper. Do not edit.
redis:
  date-retrieved: 09-02-02 10:35:48
  versions:
  - '7.1'
  - '7.2'
opensearch:
  date-retrieved: 09-12-24 16:00:00
  versions:
  - '6.1'
  - '6.2'
"""

    YamlFileProvider.write(test_path, test_content, test_comment)
    with open(test_path, "r") as test_yaml_file:
        actual_cache_file = test_yaml_file.read()
        assert expected_test_cache_file in actual_cache_file


def test_writes_with_no_comment(fs):
    test_path = "./test"
    test_content = {
        "redis": {"date-retrieved": "09-02-02 10:35:48", "versions": ["7.1", "7.2"]},
        "opensearch": {"date-retrieved": "09-12-24 16:00:00", "versions": ["6.1", "6.2"]},
    }
    expected_test_cache_file = """redis:
  date-retrieved: 09-02-02 10:35:48
  versions:
  - '7.1'
  - '7.2'
opensearch:
  date-retrieved: 09-12-24 16:00:00
  versions:
  - '6.1'
  - '6.2'
"""

    YamlFileProvider.write(test_path, test_content)
    with open(test_path, "r") as test_yaml_file:
        actual_cache_file = test_yaml_file.read()
        assert expected_test_cache_file in actual_cache_file


def test_writes_account_numbers_as_quoted_strings(fs):
    test_path = "./test"
    test_content = {
        "accounts": {
            "deploy": {"name": "account1", "id": "0123456789"},
            "dns": {"name": "account2", "id": "9876543210"},
            "other": None,
            "one_more": None,
        }
    }
    expected_test_cache_file = """accounts:
  deploy:
    name: account1
    id: '0123456789'
  dns:
    name: account2
    id: '9876543210'
  other:
  one_more:
"""

    YamlFileProvider.write(test_path, test_content)
    with open(test_path, "r") as test_yaml_file:
        assert expected_test_cache_file.strip() == test_yaml_file.read().strip()


def test_remove_empty_keys(fs):
    test_path = "./test"
    test_content = {
        "test": {
            "empty1": {},
            "empty2": [],
            "empty3": None,
            "not_empty": "name",
        }
    }
    expected_test_output_file = """test:
  not_empty: name
"""

    test_content = YamlFileProvider.remove_empty_keys(test_content)
    YamlFileProvider.write(test_path, test_content)
    with open(test_path, "r") as test_yaml_file:
        assert expected_test_output_file.strip() == test_yaml_file.read().strip()


def test_find_and_replace(fs):
    test_path = "./test"
    test_content = {
        "test": {
            "value1": "REPLACE_ME",
            "value2": "TEST_STRING_REPLACE_ME_TEST_STRING",
            "value3": {"value4": "REPLACE_ME"},
        }
    }
    expected_test_output_file = """test:
  value1: REPLACED
  value2: TEST_STRING_REPLACED_TEST_STRING
  value3:
    value4: REPLACED
"""

    test_content = YamlFileProvider.find_and_replace(test_content, "REPLACE_ME", "REPLACED")
    YamlFileProvider.write(test_path, test_content)
    with open(test_path, "r") as test_yaml_file:
        assert expected_test_output_file.strip() == test_yaml_file.read().strip()
