version: 2
updates:
  - package-ecosystem: "pip"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    commit-message:
      # So the release-please-action includes production
      # dependencies in the release notes.
      prefix: "deps"
      # Don't include dev dependencies in release notes, they
      # are of no interest outside this repository's maintainers.
      prefix-development: "chore(deps-dev)"
    groups:
      minor-and-patch:
        update-types: [minor, patch]
        applies-to: "version-updates"
        dependency-type: "production"
      dev-minor-and-patch:
        update-types: [minor, patch]
        applies-to: "version-updates"
        dependency-type: "development"

  - package-ecosystem: "terraform"
    cooldown:
      default-days: 7
    directories:
      - "/terraform/*/"
    groups:
      minor-and-patch:
        update-types: [minor, patch]
        applies-to: "version-updates"
        dependency-type: "production"
      dev-minor-and-patch:
        update-types: [minor, patch]
        applies-to: "version-updates"
        dependency-type: "development"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    commit-message:
      # So the release-please-action includes production
      # dependencies in the release notes.
      prefix: "deps"
      # Don't include dev dependencies in release notes, they
      # are of no interest outside this repository's maintainers.
      prefix-development: "chore(deps-dev)"

  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
