version: 0.2

env:
  shell: bash
  parameter-store:
    PYPI_TOKEN: "pypi-token"
    SLACK_TOKEN: "/codebuild/slack_oauth_token"
    SLACK_CHANNEL_ID: "/codebuild/slack_platform_helper_publish_oauth_channel"
    TEST_SLACK_CHANNEL_ID: "/codebuild/slack_channel_id_test_command_output"
    

phases:
  install:
    commands:
      - echo -e "\nSetting local Python versions"
      - pyenv versions | awk 'match($0, /[0-9]\.[0-9]+\.[0-9]+/) { print substr($0, RSTART, RLENGTH) }' | tac > .python-version
      - |
        echo -e "\nCheck we are using the latest installed Python 3.x"
        python --version
      - echo -e "\nInstalling dependencies"
      - pip install poetry
      - poetry install
      - pip install dbt-platform-helper

  build:
    commands:
      - echo -e "\nBuild and publish to PyPi"
      - ./publish_to_pypi.sh ${PYPI_TOKEN} ${SLACK_TOKEN} ${TEST_SLACK_CHANNEL_ID}
      
  post_build:
  commands:
    - |
      VERSION=$(python utils/check_pypi.py --version)
    - |
      if [ "$(git rev-parse --abbrev-ref HEAD)" == "DBTP-1094-platform-tools-PyPi-package-published-Slack-notification-not-working" ] && [ "${CODEBUILD_BUILD_SUCCEEDING}" == "1" ]; then
        MESSAGE=":tada: New 'platform-helper' release - *Version* ${VERSION}"
        
        platform-helper notify add-comment "${TEST_SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "" "${MESSAGE}"
      fi
