version: 0.2

env:
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token
    SLACK_CHANNEL_ID: /codebuild/slack_oauth_channel

phases:
  install:
    commands:
      - echo -e "\nSetting local Python versions"
      - pyenv versions | awk 'match($0, /[0-9]\.[0-9]+\.[0-9]+/) { print substr($0, RSTART, RLENGTH) }' | tac > .python-version
      - |
        echo -e "\nCheck we are using the latest installed Python 3.x"
        python --version
      - echo -e "\nInstalling dependencies"
      - pip install poetry
      - poetry install
      - pip install dbt-platform-helper

  build:
    commands:
      - echo -e "\nRunning regression tests"
      - ./regression_tests/pull_request_tests.sh

  post_build:
    commands:
      - |
        echo -e "\n\nSend alert if the tests have failed\n"
        echo "Debug output:"
        echo "CODEBUILD_BUILD_SUCCEEDING: ${CODEBUILD_BUILD_SUCCEEDING}"
        echo "git branch: $(git branch)"
        echo "git branch --contains \$CODEBUILD_RESOLVED_SOURCE_VERSION: $(git branch --contains $CODEBUILD_RESOLVED_SOURCE_VERSION)"
        echo "git branch --contains \$CODEBUILD_RESOLVED_SOURCE_VERSION | grep -q "main": $(git branch --contains $CODEBUILD_RESOLVED_SOURCE_VERSION | grep -q "main")"
      - |
        if [ "${CODEBUILD_BUILD_SUCCEEDING}" != "1" ] && git branch --contains $CODEBUILD_RESOLVED_SOURCE_VERSION | grep -q "main"; then
          MESSAGE=":alert: @here DBT Platform regression tests have failed in <https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/763451185160/projects/platform-tools-test/build/${CODEBUILD_BUILD_ID}/?region=eu-west-2|build ${CODEBUILD_BUILD_NUMBER}> :sob:"
          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "" "${MESSAGE}"
        fi
