version: 0.2

phases:
  install:
    commands:
      - echo -e "\nSetting local Python versions"
      - pyenv versions | awk 'match($0, /[0-9]\.[0-9]+\.[0-9]+/) { print substr($0, RSTART, RLENGTH) }' | tac > .python-version
      - |
        echo -e "\nCheck we are using the latest installed Python 3.x"
        python --version
      - echo -e "\nInstalling dependencies"
      - pip install poetry
      - poetry install

  build:
    commands:
      - echo -e "\nRunning regression tests"
      - set -e
      - export TARGET_ENVIRONMENT=${TARGET_ENVIRONMENT:-toolspr}
      - 'echo -e "\nCurrent platform-tools branch/commit: $(git rev-parse --abbrev-ref HEAD)/$(git rev-parse HEAD)"'
      - source ./regression_tests/stages/set_up_git_config.sh
      - ./regression_tests/stages/build_platform_helper.sh
      - ./regression_tests/stages/clone_demodjango_deploy.sh
      - ./regression_tests/stages/clone_demodjango.sh

artifacts:
  files:
    - "**/*"
