version: 0.2

phases:
  pre_build:
    commands:
      - echo "3.9" > .python-version
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/uktrade
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t tunnel-$ADDON_TYPE:latest --file Dockerfile.conduit.$ADDON_TYPE .
      - docker tag tunnel-$ADDON_TYPE:latest public.ecr.aws/uktrade/tunnel-$ADDON_TYPE:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/uktrade/tunnel-$ADDON_TYPE:latest
