[cosmic-ray]
module-path = "dbt_platform_helper/domain"
timeout = 10.0
excluded-modules = []
test-command = "poetry run pytest tests/platform_helper/domain"

[cosmic-ray.distributor]
name = "http"

[cosmic-ray.distributor.http]
worker-urls = [
    "http://localhost:9876",
    "http://localhost:9877",
    "http://localhost:9878",
    "http://localhost:9879"
]
