version: 0.2

env:
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token

phases:
  install:
    commands:
      - export PATH="${CODEBUILD_SRC_DIR}/build-tools/py/bin:${CODEBUILD_SRC_DIR}/build-tools/bin:$PATH"
      - export PYTHONPATH="${CODEBUILD_SRC_DIR}/build-tools/py:${PYTHONPATH}"

  pre_build:
    commands:
      # IMAGE_TAG is required to retrieve the Slack notification reference from the image
      # Check if the specified image tag exists, also fails the pipeline early if an incorrect tag is supplied
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - |
        if ! docker manifest inspect "${REPOSITORY_URL}:${IMAGE_TAG}" > /dev/null 2>&1; then
          echo "Error: Image tag ${IMAGE_TAG} not found in repository ${REPOSITORY_URL}" | tee output.log
          exit 1
        fi

      # Check environment exists in config
      - |
        if [ $(echo $ENV_CONFIG | jq 'has('\"${ENVIRONMENT}\"')') == "false" ]; then
          echo "Error: Environment ${ENVIRONMENT} not listed in environment config" | tee output.log
          exit 1
        fi

      # Check service-deployment-mode and exit early if value doesn't correspond
      - |
        ENVIRONMENT="${ENVIRONMENT}"
        PLATFORM_CONFIG_PATH="${CODEBUILD_SRC_DIR}/platform-config.yml"
        ALLOWED_MODES=("dual-deploy-copilot-traffic" "dual-deploy-platform-traffic" "platform")

        DEPLOY_MODE=$(yq eval ".environments.\"$ENVIRONMENT\".service-deployment-mode" "$PLATFORM_CONFIG_PATH")

        if [ "$DEPLOY_MODE" == "null" ] || [ -z "$DEPLOY_MODE" ]; then
          DEPLOY_MODE=$(yq eval '.environments."*".service-deployment-mode' "$PLATFORM_CONFIG_PATH")
          if [ "$DEPLOY_MODE" == "null" ] || [ -z "$DEPLOY_MODE" ]; then
            echo "Property 'service-deployment-mode' not found in platform-config. No further action required, skipping pipeline stage ..."
            export SKIP_BUILD="true"
          fi
        fi

        MATCHED=false
        for mode in "${ALLOWED_MODES[@]}"; do
          if [[ "$DEPLOY_MODE" == "$mode" ]]; then
            MATCHED=true
            break
          fi
        done

        if [ "$MATCHED" == "false" ]; then
          echo "Detected default service-deployment-mode. No further action required, skipping pipeline stage ..."
          export SKIP_BUILD="true"
        else
          echo "Property service-deployment-mode '$DEPLOY_MODE' detected. Resuming pipeline ..."
        fi

  build:
    commands:
      - |
        set -e

        # Skip pipeline if true
        if [[ "$SKIP_BUILD" == "true" ]]; then 
          echo "Skipping pipeline stage, no further action required."
        else 

          # Construct Slack message env vars

          SLACK_REF=$(regctl image config "${REPOSITORY_URL}:${IMAGE_TAG}" | jq -r '.config.Labels."uk.gov.trade.digital.build.timestamp"')
          if [ "${SLACK_REF}" = "null" ] || [ -z "${SLACK_REF}" ]; then
            echo "Error: Image contains no timestamp label" | tee output.log
            exit 1
          fi

          # Extract the pipeline name from CODEBUILD_INITIATOR default env var

          if [[ "${CODEBUILD_INITIATOR}" == codepipeline/* ]]; then 
            PIPELINE_NAME=$(echo "${CODEBUILD_INITIATOR}" | cut -d'/' -f2) 
          else 
            echo "Error: Build not triggered by CodePipeline." | tee output.log
            exit 1 
          fi

          # Construct the pipeline execution URL

          PIPELINE_EXECUTION_URL="https://${AWS_REGION}.console.aws.amazon.com/codesuite/codepipeline/pipelines/${PIPELINE_NAME}/executions/${PIPELINE_EXECUTION_ID}"
          BUILD_ID_PREFIX=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f1)

          # Send service Terraform starting Slack notification

          MESSAGE=":terraform::large_blue_circle: STARTED - Service infrastructure changes for \`${SERVICE}\` in environment \`${ENVIRONMENT}\` <https://${AWS_REGION}.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=${AWS_REGION}|Build log> | <${PIPELINE_EXECUTION_URL}|Pipeline execution>"
          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"

          # Assume environment role
        
          account_id=$(echo ${ENV_CONFIG} | jq -c -r .${ENVIRONMENT}.account_id)
          account_name=$(echo ${ENV_CONFIG} | jq -c -r .${ENVIRONMENT}.account_name)
          assumed_role=$(aws sts assume-role --role-arn "arn:aws:iam::${account_id}:role/${APPLICATION}-${ENVIRONMENT}-codebase-pipeline-deploy" --role-session-name "${ENVIRONMENT}-codebase-pipeline-deploy")
          export AWS_ACCESS_KEY_ID=$(echo $assumed_role | jq -r .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $assumed_role | jq -r .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $assumed_role | jq -r .Credentials.SessionToken)
        
          # Set an AWS profile for Terraform
        
          PROFILE_NAME="${account_name}"
          aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}" --profile "${PROFILE_NAME}"
          aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}" --profile "${PROFILE_NAME}"
          aws configure set aws_session_token "${AWS_SESSION_TOKEN}" --profile "${PROFILE_NAME}"
          aws configure set region "eu-west-2" --profile "${PROFILE_NAME}"
          aws configure set output "json" --profile "${PROFILE_NAME}"
          export AWS_PROFILE="${PROFILE_NAME}"

          # Generate service Terraform and apply it
        
          cd "${CODEBUILD_SRC_DIR}"
          local_ecs_service_path=../../../../platform-tools/terraform/ecs-service
          TERRAFORM_MODULE_SOURCE_TYPE=OVERRIDE TERRAFORM_ECS_SERVICE_MODULE_SOURCE_OVERRIDE=${local_ecs_service_path} platform-helper internal service generate --env "${ENVIRONMENT}" --name "${SERVICE}"
          cd "${CODEBUILD_SRC_DIR}/terraform/services/${ENVIRONMENT}/${SERVICE}"
          terraform init
          terraform apply -auto-approve

          # Send Slack message on pipeline outcome
          
          if [ $? -eq 0 ]; then
            deploy_status="SUCCESSFUL"
            STATUS_EMOJI=":large_green_circle:"
            STATUS_TEXT="COMPLETE"
            SEND_TO_MAIN_CHANNEL="false"
          else
            deploy_status="FAILED"
            STATUS_EMOJI=":red_circle:"
            STATUS_TEXT="FAILED"
            SEND_TO_MAIN_CHANNEL="true"
          fi

          # Send notification on successful deployment or exit with an error code
        
          if [ "${deploy_status}" == "SUCCESSFUL" ]; then
            MESSAGE=":terraform:${STATUS_EMOJI} ${STATUS_TEXT} - Service infrastructure changes for \`${SERVICE}\` in environment \`${ENVIRONMENT}\` <https://${AWS_REGION}.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=${AWS_REGION}|Build log> | <${PIPELINE_EXECUTION_URL}|Pipeline execution>"
            platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}" --send-to-main-channel "${SEND_TO_MAIN_CHANNEL}"
          else
            echo "Error: Deployment status is ${deploy_status}" | tee output.log
            exit 1
          fi
        fi

  post_build:
    commands:
      - |
        if [ "${CODEBUILD_BUILD_SUCCEEDING}" != "1" ]; then
          BUILD_ID_PREFIX=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f1)          
          MESSAGE=":terraform::red_circle: FAILED - Service infrastructure changes for service \`${SERVICE}\` in environment \`${ENVIRONMENT}\` - $(cat output.log) - <https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=eu-west-2|Build log>"
          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}" --send-to-main-channel true
        fi
