version: 0.2

env:
  variables:
    DEPLOY_TIMEOUT: 1800
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token

phases:
  install:
    commands:

  build:
    commands:
      # Need to find out how many distributions should be touched
      - set -e
      - export CONFIG_JSON='{"api.kate.demodjango.uktrade.digital": {"paths": ["a/*", "b/*"]}, "web.kate.demodjango.uktrade.digital": {}'

      #- loop through domains:
      #- for each domain get associated PATHS from CONFIG_JSON using jq
      #- DOMAIN="api.kate.demodjango.uktrade.digital"
      #- PATHS="a/* b/*"
      - invalidate-cache.sh ${DOMAIN} ${PATHS}

  post_build:
    commands:
      - echo "DONE"