version: 0.2

env:
  variables:
    DEPLOY_TIMEOUT: 1800
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token

phases:
  install:
    commands:

  build:
    commands:
      - export DNS_ACCOUNT_ID=$(echo ${ENV_CONFIG} | jq -r --arg env ${ENVIRONMENT} '.[$env].dns_account')
      - |
        set -e

        echo -e "\nAssume role in ${DNS_ACCOUNT_ID} account"
        assumed_role=$(aws sts assume-role --role-arn "arn:aws:iam::${DNS_ACCOUNT_ID}:role/environment-pipeline-assumed-role" --role-session-name "${APPLICATION}-${ENVIRONMENT}-cdn-cache-invalidation")
        export AWS_ACCESS_KEY_ID=$(echo $assumed_role | jq -r .Credentials.AccessKeyId)
        export AWS_SECRET_ACCESS_KEY=$(echo $assumed_role | jq -r .Credentials.SecretAccessKey)
        export AWS_SESSION_TOKEN=$(echo $assumed_role | jq -r .Credentials.SessionToken)
      
        # Invalidate caches
        ENV_CACHE_INVALIDATION_CONFIG=$(echo $CONFIG_JSON | jq -r --arg env ${ENVIRONMENT} '.[$env]')
        DOMAINS=$(echo $ENV_CACHE_INVALIDATION_CONFIG | jq -r 'keys[]')

        for i in ${DOMAINS}; do
          echo "Getting distribution ID for domain ${i}"
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query 'DistributionList.Items' --output json | jq -r --arg domain "$i" '.[] | select(.Aliases.Items != null and .Aliases.Items[0] == $domain) | .Id')
          PATHS=$(echo $ENV_CACHE_INVALIDATION_CONFIG | jq -r --arg domain ${i} '.[$domain] | join(" ")')
          
          if [ -z ${DISTRIBUTION_ID} ]: then
            echo "ERROR: No distribution ID found for domain ${i} in account ${DNS_ACCOUNT_ID}.  Please check cache_invalidation configuration.  Exiting."
            exit 1
          fi
          
          echo -e "\nInvalidating the cache in distibution id ${DISTRIBUTION_ID} for paths ${PATHS}\n"
          aws cloudfront create-invalidation \
          --distribution-id $DISTRIBUTION_ID \
          --paths $PATHS
        done
      #TODO check for any alias=domain, instead of just the first item
  post_build:
    commands:
      - echo "DONE"
