version: 0.2

env:
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token

phases:
  build:
    commands:
    - >
        if [ -f ./custom-build/post-deploy.sh ]; then 
          bash ./custom-build/post-deploy.sh; 
        fi

  post_build:
    commands:
    - echo "Done"
