version: 0.2

phases:
  build:
    commands:
    - >
        if [ -f ./custom-build/pre-deploy.sh ]; then 
          bash ./custom-build/pre-deploy.sh; 
        fi

  post_build:
    commands:
    - echo "Done"
