version: 0.2

phases:
  build:
    commands:
    - >
        if [ -f ./custom-build/post-build.sh ]; then 
          bash ./custom-build/post-build.sh; 
        fi

  post_build:
    commands:
    - echo "Done"
