version: 0.2

env:
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token
  variables:
    TERRAFORM_VERSION: 1.12.2
  exported-variables:
    - SLACK_REF

phases:
  install:
    commands:
      - set -e
      - cd "${CODEBUILD_SRC_DIR}"
      - mkdir -p ./build-tools/bin
      - mkdir -p ./build-tools/py
      - export PATH="${CODEBUILD_SRC_DIR}/build-tools/bin:$PATH"
      ## yq for yaml processing (The Go-based variant, not Python-based)
      - curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o ./build-tools/bin/yq
      - chmod +x ./build-tools/bin/yq
      ## regctl for listing images
      - curl -sL https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 -o ./build-tools/bin/regctl
      - chmod +x ./build-tools/bin/regctl
      ## Check for platform-helper version override
      ## TODO 
      ## REQUIRED_VERSION is latest, not from config (which would give "auto")
      ## OR PLATFORM_HELPER_VERSION must be set and must be latest if "auto"
      - |
         if [ "${PLATFORM_HELPER_VERSION}" == "NONE" ]; then
           echo "Install platform-helper version from platform-config default version"  
           REQUIRED_VERSION=$(yq eval ".default_versions.platform-helper" platform-config.yml)
         else
           REQUIRED_VERSION="${PLATFORM_HELPER_VERSION}"
         fi
      ## Resolve COMMIT_TYPE for auto   
      - COMMIT_TYPE=$(python -c "import re, sys; print('tag' if re.match(r'\\d+\\.\\d+\\.\\d+', '${REQUIRED_VERSION}') else 'commit')")
      - echo "Installing build tools"

      # Install platform-helper
      - echo "Installing platform-helper from reference ${REQUIRED_VERSION}"
      ## Clone platform-tools:
      - echo -e "\nGet CodeStar connection details"
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - codestar_connection_id=$(echo "${CODESTAR_CONNECTION_ARN##*/}")
      - export GIT_CLONE_BASE_URL="https://codestar-connections.${AWS_REGION}.amazonaws.com/git-http/${AWS_ACCOUNT_ID}/${AWS_REGION}/$codestar_connection_id/uktrade"
      - git clone "${GIT_CLONE_BASE_URL}/platform-tools.git" --branch "${REQUIRED_VERSION}" --depth 1 platform-tools
      ## Install platform-helper
      - cd platform-tools
      - pip install poetry --quiet
      - poetry build --no-interaction --format sdist --no-ansi | tee build-log.txt
      - ARTIFACT=$(grep "Built dbt_platform_helper-.*tar.gz" build-log.txt | sed "s/.*Built //")
      - 'echo "Package archive: $ARTIFACT"'
      - cd "${CODEBUILD_SRC_DIR}/build-tools"
      - pip install --upgrade --target "${CODEBUILD_SRC_DIR}/build-tools/py" --quiet "${CODEBUILD_SRC_DIR}/platform-tools/dist/${ARTIFACT}"
      - VERSION_OUTPUT=""
      - export PATH="${CODEBUILD_SRC_DIR}/build-tools/py/bin:${CODEBUILD_SRC_DIR}/build-tools/bin:$PATH"
      - export PYTHONPATH="${CODEBUILD_SRC_DIR}/build-tools/py:${PYTHONPATH}"
      - platform-helper --version
      - cd bin
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_install.zip
      - chmod +x terraform
      - rm terraform_install.zip
      - VERSION_OUTPUT+="\n$(terraform --version)"
      - VERSION_OUTPUT+="\n$(platform-helper --version)"
      - if [ "${COMMIT_TYPE}" != "tag" ]; then VERSION_OUTPUT+=" (from git ref ${REQUIRED_VERSION})"; fi
      - VERSION_OUTPUT+="\n$(python3 --version)"
      - VERSION_OUTPUT+="\n$(pip --version)"
      - echo -e "=============\nTool Versions\n-------------\n$VERSION_OUTPUT"
artifacts:
  files:
    - "**/*"
