version: 0.2

env:
  variables:
    DEPLOY_TIMEOUT: 1800
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token

phases:
  install:
    commands:

  build:
    commands:
      # Need to find out how many distributions should be touched
      - set -e
      - CONFIG_JSON="TEST"
      - invalidate-cache.sh ${CONFIG_JSON}

  post_build:
    commands:
      - echo "DONE"