version: 0.2

env:
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token
  exported-variables:
    - BUILD_ID

phases:
  install:
    commands:
      - export PATH="${CODEBUILD_SRC_DIR}/build-tools/bin:$PATH"
      - export PYTHONPATH="${CODEBUILD_SRC_DIR}/build-tools"
  build:
    commands:
      - set -e
      # Cancel pending approvals
      - echo "Cancelling any pending approvals for ${APPLICATION}-${ENVIRONMENT}-environment-pipeline"
      - PIPELINE_STATE=$(aws codepipeline get-pipeline-state --name "${APPLICATION}-${PIPELINE_NAME}-environment-pipeline")
      - PIPELINE_APPROVAL_EXECID=$(echo $PIPELINE_STATE | jq  --arg stage "Approve-${ENVIRONMENT}" -r '.stageStates[] | select(.stageName == $stage and .latestExecution.status == "InProgress") | .latestExecution.pipelineExecutionId')
      - |
        if [ -n "${PIPELINE_APPROVAL_EXECID}" ]; then
          aws codepipeline stop-pipeline-execution --pipeline-name "${APPLICATION}-${PIPELINE_NAME}-environment-pipeline" --pipeline-execution-id $PIPELINE_APPROVAL_EXECID --abandon --reason "Abandoning previous pipeline execution pending approval to run terraform plan" 
        fi
      - echo "Terraform Plan Phase"
      - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Starting terraform plan phase for the ${ENVIRONMENT} environment."
      - echo "Working on environment ${ENVIRONMENT}"
      # Generate environment manifest
      - platform-helper environment generate-terraform --name "${ENVIRONMENT}"
      # Run plan
      - cd terraform/environments/${ENVIRONMENT}
      # Hack main.tf to point at local copy. TODO: Replace me with the env var for changing the source before generating the terraform above!
      - 'sed -i ''s#source.*https://github.com/uktrade/platform-tools.git.*#source": "../../../platform-tools/terraform/extensions",#'' main.tf.json'
      - terraform init
      - terraform plan -out=plan.tfplan
  post_build:
    commands:
      - export BUILD_ID="$CODEBUILD_BUILD_ID"
      - |
        if [ "${CODEBUILD_BUILD_SUCCEEDING}" == "1" ]; then
          MESSAGE="Terraform plan phase complete for the ${ENVIRONMENT} environment."
          if [ "${NEEDS_APPROVAL}" == "yes" ]; then
            MESSAGE="${MESSAGE} Waiting for approval for the ${ENVIRONMENT} environment."
          fi
          ADDITIONAL_OPTIONS=""
        else
          MESSAGE=":alert: Terraform plan phase FAILED for the ${ENVIRONMENT} environment."
          ADDITIONAL_OPTIONS="--send-to-main-channel true"
        fi
      - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}" ${ADDITIONAL_OPTIONS}
artifacts:
  files:
    - "**/*"
