import datetime
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version

from jinja2_simple_tags import StandaloneTag


class VersionTag(StandaloneTag):
    tags = {"version_info"}

    def _get_version(self):
        try:
            return version("dbt-copilot-tools")
        except PackageNotFoundError:
            return "UNKNOWN"

    def render(self):
        format = "%Y-%m-%d %H:%M:%S"
        time = datetime.datetime.now().strftime(format)
        return f"Generated by copilot-helper {self._get_version()} / {time}"
