from unittest.mock import Mock

import pytest

from dbt_platform_helper.domain.config import Config
from dbt_platform_helper.domain.config import NoDeploymentRepoConfigException
from dbt_platform_helper.providers.io import ClickIOProvider


class ConfigMocks:
    def __init__(self, *args, **kwargs):
        self.io = kwargs.get("io", Mock(spec=ClickIOProvider))

    def params(self):
        return dict(io=self.io)


class TestConfigValidate:

    def test_validate(self, fakefs):
        fakefs.create_file(
            "/copilot/environments/dev/addons/test_addon.yml",
            contents="# Generated by platform-helper v0.1.0",
        )

        config_mocks = ConfigMocks()
        config_domain = Config(**config_mocks.params())
        config_domain.validate()

        config_mocks.io.debug.assert_called_with("\nDetected a deployment repository")

    def test_no_repo(self, fakefs):
        config_domain = Config()
        with pytest.raises(
            NoDeploymentRepoConfigException,
            match="Could not find a deployment repository, no checks to run.",
        ):
            config_domain.validate()


class TestConfigGenerateAWS:
    pass
