version: 0.2
env:
  git-credential-helper: yes
  parameter-store:
    SLACK_CHANNEL_ID: /codebuild/slack_oauth_channel
    SLACK_TOKEN: /codebuild/slack_oauth_token
    TEST_SLACK_CHANNEL_ID: /codebuild/slack_channel_id_test_command_output
  variables:
    COLOR: false
    CI: true
phases:
  build:
    commands:
      - |
        environments="{{environments}}"
        echo "Environments are - ${environments}"
        if echo ",${environments}," | grep -q ",${COPILOT_ENVIRONMENT},"; then
          echo "Deploy environment is ${COPILOT_ENVIRONMENT}"
          /work/cli deploy --send-notifications
        else
          exit 1
        fi
  
  post_build:
    commands:
      - |
        if [ "${CODEBUILD_BUILD_SUCCEEDING}" != "1" ]; then
          BUILD_ID_PREFIX=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f1)
          echo "BUILD_ID_PREFIX - ${BUILD_ID_PREFIX}"
          
          echo -e "\nInstalling dependencies"
          pip install dbt-platform-helper
          
          MESSAGE=":no_entry::construction: Build failure in codebuid project: <https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=eu-west-2|${BUILD_ID_PREFIX} - build ${CODEBUILD_BUILD_NUMBER}>"
          
          platform-helper notify add-comment "${TEST_SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "" "${MESSAGE}"
        fi
