version: 0.2

env:
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token
    SLACK_CHANNEL_ID: /codebuild/slack_oauth_channel

phases:
  install:
    commands:
      - echo -e "\nSetting local Python versions"
      - pyenv versions | awk 'match($0, /[0-9]\.[0-9]+\.[0-9]+/) { print substr($0, RSTART, RLENGTH) }' | tac > .python-version
      - |
        echo -e "\nCheck we are using the latest installed Python 3.x"
        python --version
      - echo -e "\nInstalling dependencies"
      - pip install poetry
      - poetry install
      - pip install dbt-platform-helper
      - echo "Current working directory - check regression_tests/stages"
      - ls -la ./regression_tests/stages/

  build:
    commands:
      - echo -e "\nRunning regression tests - Build stage\n"
      - echo "Current working directory - Build phase"
      - pwd
#      - ls -la
      - source .regression_tests/stages/set_up_git_config.sh
      - .regression_tests/stages/clone_demodjango_deploy.sh
      - .regression_tests/stages/clone_demodjango.sh
      - .regression_tests/stages/build_platform_helper.sh

  post_build:
    commands:
      - |
        if [ "${CODEBUILD_BUILD_SUCCEEDING}" != "1" ] && git branch --contains $CODEBUILD_RESOLVED_SOURCE_VERSION | grep -q "main"; then
          MESSAGE=":alert: @here DBT Platform regression tests have failed in <https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/763451185160/projects/platform-tools-test/build/${CODEBUILD_BUILD_ID}/?region=eu-west-2|build ${CODEBUILD_BUILD_NUMBER}> :sob:"
          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "" "${MESSAGE}"
        fi

# Does this buildspec require an "artifacts" section??