version: 0.2

env:
  parameter-store:
    SLACK_CHANNEL_ID: /codebuild/slack_oauth_channel
    SLACK_TOKEN: /codebuild/slack_oauth_token
  exported-variables:
    - SLACK_REF

phases:
  install:
    commands:
      - set -e
      - echo "Installing tools for ${PIPELINE_NAME}"
      - pip install yq --quiet
      - cd "${CODEBUILD_SRC_DIR}"
      - |
        if [ "${PLATFORM_HELPER_VERSION_OVERRIDE}" == "NONE" ]; then
          echo "Install platform-helper version from platform-config default version"
          REQUIRED_VERSION=$(yq -r '.default_versions.["platform-helper"]' platform-config.yml)
        else
          REQUIRED_VERSION="${PLATFORM_HELPER_VERSION_OVERRIDE}"
        fi
      - echo "Installing build tools"
      - mkdir ./build-tools

      # Install platform-helper
      - echo "Installing platform-helper from reference ${REQUIRED_VERSION}"
      ## Clone platform-tools:
      - echo -e "\nGet CodeStar connection details"
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - codestar_connection_id=$(echo "${CODESTAR_CONNECTION_ARN##*/}")
      - export GIT_CLONE_BASE_URL="https://codestar-connections.${AWS_REGION}.amazonaws.com/git-http/${AWS_ACCOUNT_ID}/${AWS_REGION}/$codestar_connection_id/uktrade"
      - git clone "${GIT_CLONE_BASE_URL}/platform-tools.git" --branch "${REQUIRED_VERSION}" --depth 1 platform-tools
      ## Install platform-helper
      - cd platform-tools
      - pip install poetry --quiet
      - poetry build --no-interaction --format sdist --no-ansi | tee build-log.txt
      - ARTIFACT=$(grep "Built dbt_platform_helper-.*tar.gz" build-log.txt | sed "s/.*Built //")
      - 'echo "Package archive: $ARTIFACT"'
      - cd "${CODEBUILD_SRC_DIR}/build-tools"
      - pip install --target . --quiet "${CODEBUILD_SRC_DIR}/platform-tools/dist/${ARTIFACT}"
      - VERSION_OUTPUT=""
      - export "PATH=$(pwd)/bin:$PATH"
      - export PYTHONPATH=$(pwd)
      - platform-helper --version
      - | 
          export SLACK_REF=$(platform-helper notify environment-progress "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" \
          "Starting database copy for ${DATABASE_NAME} from ${FROM_ENVIRONMENT} to ${TO_ENVIRONMENT}")
      - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Install phase complete"
artifacts:
  files:
    - "**/*"
