# {% version_info %}
Parameters:
  # Copilot required Parameters...
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.

  # Parameters from the parent stack brought in via addons.parameters.yml...
  EnvironmentSecurityGroup:
    Type: String
  PrivateSubnets:
    Type: String
  VpcId:
    Type: String

  # Other parameters...
  # Customize your Aurora Postgres cluster by setting the default value of the following parameters.
  {{ service.prefix }}DBName:
    Type: String
    Description: The name of the initial database to be created in the Aurora Serverless v2 cluster.
    Default: main
    # Cannot have special characters
    # Naming constraints: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints

Mappings:
  {{ service.prefix }}EnvScalingConfigurationMap:
{% for environment_name, config in service.environments.items() %}
    {{ environment_name }}:
      DBMinCapacity: {{ config.min_capacity }}
      DBMaxCapacity: {{ config.max_capacity }}
{% endfor %}

Resources:
  {{ service.prefix }}DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Group of Copilot private subnets for Aurora Serverless v2 cluster.
      SubnetIds: !Split [ ",", !Ref PrivateSubnets ]

  {{ service.prefix }}SecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your workload to access the Aurora Serverless v2 cluster {{ service.prefix }}'
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'The Security Group for {{ service.name }} to access Aurora Serverless v2 cluster {{ service.prefix }}.'
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-{{ service.name }}-Aurora'

  {{ service.prefix }}DBClusterSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your Aurora Serverless v2 cluster {{ service.prefix }}'
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the Aurora Serverless v2 cluster.
      SecurityGroupIngress:
        - ToPort: 5432
          FromPort: 5432
          IpProtocol: tcp
          Description: 'From the Aurora Security Group of the workload {{ service.name }}.'
          SourceSecurityGroupId: !Ref {{ service.prefix }}SecurityGroup
      VpcId: !Ref VpcId

  {{ service.prefix }}AuroraSecret:
    Metadata:
      'aws:copilot:description': 'A Secrets Manager secret to store your DB credentials'
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/copilot/${App}/${Env}/secrets/{{ service.name|upper|replace("-", "_") }}'
      Description: !Sub Aurora main user secret for ${AWS::StackName}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
        ExcludeCharacters: '[]{}()"@/\;=?&`><:|#'

  {{ service.prefix }}DBClusterParameterGroup:
    Metadata:
      'aws:copilot:description': 'A DB parameter group for engine configuration values'
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: !Ref 'AWS::StackName'
      Family: 'aurora-postgresql{{ service.version|round(0, "floor")|int }}'
      Parameters:
        client_encoding: 'UTF8'
        log_statement: ddl
        log_statement_sample_rate: '1.0'

  {{ service.prefix }}DBCluster:
    Metadata:
      'aws:copilot:description': 'The {{ service.prefix }} Aurora Serverless v2 database cluster'
    Type: 'AWS::RDS::DBCluster'
    Properties:
      AutoMinorVersionUpgrade: true
      MasterUsername:
        !Join [ "",  [ '{% raw %}{{{% endraw %}resolve:secretsmanager:', !Ref {{ service.prefix }}AuroraSecret, ":SecretString:username{% raw %}}}{% endraw %}" ]]
      MasterUserPassword:
        !Join [ "",  [ '{% raw %}{{{% endraw %}resolve:secretsmanager:', !Ref {{ service.prefix }}AuroraSecret, ":SecretString:password{% raw %}}}{% endraw %}" ]]
      DatabaseName: !Ref {{ service.prefix }}DBName
      Engine: 'aurora-postgresql'
      EngineVersion: '{{ service.version }}'
      EnableCloudwatchLogsExports:
        - postgresql
      DBClusterParameterGroupName: !Ref {{ service.prefix }}DBClusterParameterGroup
      DBSubnetGroupName: !Ref {{ service.prefix }}DBSubnetGroup
      Port: 5432
      VpcSecurityGroupIds:
        - !Ref {{ service.prefix }}DBClusterSecurityGroup
      ServerlessV2ScalingConfiguration:
        MinCapacity: !FindInMap [{{ service.prefix }}EnvScalingConfigurationMap, !Ref Env, DBMinCapacity]
        MaxCapacity: !FindInMap [{{ service.prefix }}EnvScalingConfigurationMap, !Ref Env, DBMaxCapacity]
      StorageEncrypted: true

  {{ service.prefix }}DBWriterInstance:
    Metadata:
      'aws:copilot:description': 'The {{ service.prefix }} Aurora Serverless v2 writer instance'
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBClusterIdentifier: !Ref {{ service.prefix }}DBCluster
      DBInstanceClass: db.serverless
      EnablePerformanceInsights: true
      Engine: 'aurora-postgresql'
      PromotionTier: 1
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region

  {{ service.prefix }}SecretAuroraClusterAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref {{ service.prefix }}AuroraSecret
      TargetId: !Ref {{ service.prefix }}DBCluster
      TargetType: AWS::RDS::DBCluster

  # Enable ingress from other ECS services created within the environment.
  {{ service.prefix }}EnvironmentIngress:
    Metadata:
      'aws:copilot:description': 'Allow ingress from containers in my application to the OpenSearch cluster'
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress Security Group from Fargate containers
      GroupId: !Ref '{{ service.prefix }}DBClusterSecurityGroup'
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref EnvironmentSecurityGroup

  # Enable ingress from Lambda Functions.
  {{ service.prefix }}LambdaIngress:
    Metadata:
      'aws:copilot:description': 'Allow ingress from Lambda functions in my application to the DB cluster'
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from Lambda Function
      GroupId: !Ref '{{ service.prefix }}DBClusterSecurityGroup'
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref '{{ service.prefix }}DBClusterSecurityGroup'

  # Enable ingress from Secrets Manager.
  {{ service.prefix }}SecretsManagerIngress:
    Metadata:
      'aws:copilot:description': 'Allow ingress from Secrets Manager in my application to the DB cluster'
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from Secrets Manager
      GroupId: !Ref '{{ service.prefix }}DBClusterSecurityGroup'
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourceSecurityGroupId: !Ref '{{ service.prefix }}DBClusterSecurityGroup'

  # Enable egress from Lambda Function.
  {{ service.prefix }}LambdaEgress:
    Metadata:
      'aws:copilot:description': 'Allow egress from Lambda functions in my application to the DB cluster'
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: Egress from Lambda Function
      GroupId: !Ref '{{ service.prefix }}DBClusterSecurityGroup'
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      DestinationSecurityGroupId: !Ref '{{ service.prefix }}DBClusterSecurityGroup'

  # Enable egress from Secrets Manager.
  {{ service.prefix }}SecretsManagerEgress:
    Metadata:
      'aws:copilot:description': 'Allow egress from Secrets Manager in my application to the DB cluster'
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: Egress from Secrets Manager
      GroupId: !Ref '{{ service.prefix }}DBClusterSecurityGroup'
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      DestinationSecurityGroupId: !Ref '{{ service.prefix }}DBClusterSecurityGroup'

  {{ service.prefix }}LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${App}-${Env}-aurora-create-application-user"
      Handler: index.handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:eu-west-2:763451185160:layer:python-postgres:1
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt {{ service.prefix }}LambdaFunctionExecutionRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref {{ service.prefix }}DBClusterSecurityGroup
        SubnetIds: !Split [ ",", !Ref PrivateSubnets ]
      Code:
        ZipFile: |
          import json

          import boto3
          import cfnresponse
          import psycopg2
          
          
          def drop_user(cursor):
              cursor.execute("SELECT * FROM pg_catalog.pg_user WHERE usename = 'application_user'")
          
              if cursor.fetchone() is not None:
                  cursor.execute("GRANT application_user TO postgres")
                  cursor.execute("DROP OWNED BY application_user")
                  cursor.execute("DROP USER application_user")
          
          
          def create_db_user(conn, cursor, password):
              drop_user(cursor)
          
              cursor.execute("CREATE USER application_user WITH ENCRYPTED PASSWORD '%s'" % password)
              cursor.execute(
                  "GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER ON ALL TABLES IN SCHEMA public TO application_user;")
              cursor.execute("GRANT application_user to postgres;")
              cursor.execute(
                  "ALTER DEFAULT PRIVILEGES FOR USER application_user IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER ON TABLES TO application_user;")
              conn.commit()
          
          
          def handler(event, context):
              print("REQUEST RECEIVED:\n" + json.dumps(event))
          
              db_master_user_secret = event['ResourceProperties']['MasterUserSecret']
              application_user_secret_name = event['ResourceProperties']['SecretName']
              application_user_secret_description = event['ResourceProperties']['SecretDescription']
              copilot_application = event['ResourceProperties']['CopilotApplication']
              copilot_environment = event['ResourceProperties']['CopilotEnvironment']
          
              secrets_manager = boto3.client("secretsmanager")
          
              master_user = json.loads(secrets_manager.get_secret_value(SecretId=db_master_user_secret)["SecretString"])
          
              application_user_password = secrets_manager.get_random_password(
                  PasswordLength=16,
                  ExcludeCharacters='[]{}()"@/\;=?&`><:|#',
                  ExcludePunctuation=True,
                  IncludeSpace=False,
              )["RandomPassword"]
          
              application_user_secret_string = {
                  "username": "application_user",
                  "password": application_user_password,
                  "engine": master_user["engine"],
                  "port": master_user["port"],
                  "dbname": master_user["dbname"],
                  "host": master_user["host"],
                  "dbClusterIdentifier": master_user["dbClusterIdentifier"]
              }
          
              conn = psycopg2.connect(
                  dbname=master_user["dbname"],
                  user=master_user["username"],
                  password=master_user["password"],
                  host=master_user["host"],
                  port=master_user["port"]
              )
          
              cursor = conn.cursor()
          
              response = {"Status": "SUCCESS"}
          
              try:
                  match event["RequestType"]:
                      case "Create":
                          create_db_user(conn, cursor, application_user_password)
          
                          response = {
                              **response,
                              "Data": secrets_manager.create_secret(
                                  Name=application_user_secret_name,
                                  Description=application_user_secret_description,
                                  SecretString=json.dumps(application_user_secret_string),
                                  Tags=[
                                      {'Key': 'custom:cloudformation:stack-name', 'Value': event["StackId"].split('/')[1]},
                                      {'Key': 'custom:cloudformation:logical-id', 'Value': event["LogicalResourceId"]},
                                      {'Key': 'custom:cloudformation:stack-d', 'Value': event["StackId"]},
                                      {'Key': 'copilot-application', 'Value': copilot_application},
                                      {'Key': 'copilot-environment', 'Value': copilot_environment},
                                  ],
                              )
                          }
                      case "Update":
                          create_db_user(conn, cursor, application_user_password)
          
                          response = {
                              **response,
                              "Data": secrets_manager.update_secret(
                                  SecretId=application_user_secret_name,
                                  SecretString=json.dumps(application_user_secret_string),
                              )
                          }
                      case "Delete":
                          drop_user(cursor)
          
                          response = {
                              **response,
                              "Data": secrets_manager.delete_secret(
                                  SecretId=application_user_secret_name,
                                  ForceDeleteWithoutRecovery=True,
                              )
                          }
                      case _:
                          response = {"Status": "FAILED",
                                      "Data": {"Error": f"""Invalid requestType of '${event["RequestType"]}'"""}}
              except Exception as e:
                  response = {"Status": "FAILED", "Data": {"Error": str(e)}}
          
              cursor.close()
              conn.close()
          
              print(json.dumps(response, default=str))
              cfnresponse.send(event, context, response["Status"], json.dumps(response["Data"], default=str),
                               event["LogicalResourceId"])

  {{ service.prefix }}ApplicationUser:
    Type: 'Custom::{{ service.prefix }}ApplicationUser'
    Properties:
      ServiceToken: !GetAtt '{{ service.prefix }}LambdaFunction.Arn'
      CopilotApplication: !Sub "${App}"
      CopilotEnvironment: !Sub "${Env}"
      MasterUserSecret: !Ref {{ service.prefix }}AuroraSecret
      SecretDescription: !Sub Aurora application user secret for ${AWS::StackName}
      SecretName: !Sub '/copilot/${App}/${Env}/secrets/{{ service.name|upper|replace("-", "_") }}_APPLICATION_USER'

  {{ service.prefix }}LambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${App}-${Env}-aurora-application-user"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: !Sub "${App}-${Env}-aurora-application-user"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DeleteNetworkInterface'
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - 'secretsmanager:CreateSecret'
                  - 'secretsmanager:TagResource'
                  - 'secretsmanager:UpdateSecret'
                  - 'secretsmanager:DeleteSecret'
                  - 'secretsmanager:DescribeSecret'
                  - 'secretsmanager:GetRandomPassword'
                  - 'secretsmanager:GetSecretValue'
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
