# {% version_info %}

Parameters:
  # Copilot required Parameters...
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.

Mappings:
  {{ service.prefix }}EnvironmentConfigMap:
    # Create an entry for each environment
{% for env_name, config in service.environments.items() %}
    {{ env_name }}:
      BucketName: '{{ config.bucket_name }}'
      DeletionPolicy: {{ config.deletion_policy }}
{% endfor %}

Resources:
  {{ service.prefix }}KMSKey:
    Type: "AWS::KMS::Key"
    DeletionPolicy: !FindInMap [{{ service.prefix }}EnvironmentConfigMap, !Ref Env, DeletionPolicy]
    UpdateReplacePolicy: Retain
    Properties:
      Description: "KMS Key for RDS encryption"
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Sub '${App}-${Env}-{{ service.prefix }}-key'
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
          Action: kms:*
          Resource: '*'

  {{ service.prefix }}KeyAlias:
    Type: 'AWS::KMS::Alias'
    DeletionPolicy: !FindInMap [{{ service.prefix }}EnvironmentConfigMap, !Ref Env, DeletionPolicy]
    UpdateReplacePolicy: Retain
    Properties:
      AliasName: !Sub 'alias/${App}-${Env}-{{ service.prefix }}-key'
      TargetKeyId: !Ref {{ service.prefix }}KMSKey

  {{ service.prefix }}Bucket:
    Metadata:
      'aws:copilot:description': 'An Amazon S3 bucket to store and retrieve objects for {{ service.prefix }}'
    Type: AWS::S3::Bucket
    DeletionPolicy: !FindInMap [{{ service.prefix }}EnvironmentConfigMap, !Ref Env, DeletionPolicy]
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !FindInMap [{{ service.prefix }}EnvironmentConfigMap, !Ref Env, BucketName]
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
            KMSMasterKeyID: !Ref {{ service.prefix }}KMSKey
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Copilot-application
          Value: !Ref App
        - Key: Copilot-environment
          Value: !Ref Env
        - Key: Copilot-deletion-policy
          Value: !FindInMap [{{ service.prefix }}EnvironmentConfigMap, !Ref Env, DeletionPolicy]

  {{ service.prefix }}BucketPolicy:
    Metadata:
      'aws:copilot:description': 'A bucket policy to deny unencrypted access to the bucket and its contents'
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !FindInMap [{{ service.prefix }}EnvironmentConfigMap, !Ref Env, DeletionPolicy]
    UpdateReplacePolicy: Retain
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ForceHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub ${ {{ service.prefix }}Bucket.Arn}/*
              - !Sub ${ {{ service.prefix }}Bucket.Arn}
            Condition:
              Bool:
                "aws:SecureTransport": false
      Bucket: !Ref {{ service.prefix }}Bucket

{% if 'objects' in service %}
  {{ service.prefix }}S3ObjectUploader:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${App}-${Env}-object-uploader"
      Handler: index.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt {{ service.prefix }}S3ObjectUploaderRole.Arn
      Code:
        ZipFile: |
{{ service.custom_resources.s3_object(10) }}

  {{ service.prefix }}S3ObjectUploaderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${App}-${Env}-object-uploader-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: !Sub "${App}-${Env}-object-uploader-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                Resource:
                  - !Sub ${ dwS3BucketBucket.Arn }/*
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

{% for s3object in service.objects %}
  {{ service.prefix }}S3Object{{ loop.index0 }}:
    Type: 'Custom::S3ObjectUploader'
    Properties:
      ServiceToken: !GetAtt {{ service.prefix }}S3ObjectUploader.Arn
      CopilotApplication: !Sub "${App}"
      CopilotEnvironment: !Sub "${Env}"
      S3Bucket: !Ref {{ service.prefix }}Bucket
      S3ObjectKey: {{ s3object.key }}
      S3ObjectBody: {{ s3object.body }}
{% endfor %}
{% endif %}

Outputs:
  {{ service.prefix }}Name:
    Description: "The name of a user-defined bucket."
    Value: !Ref {{ service.prefix }}Bucket

  {{ service.prefix }}KMSKeyARN:
    Description: "ARN of the KMS Key"
    Value: !GetAtt {{ service.prefix }}KMSKey.Arn
    Export:
      Name: !Sub "${App}-${Env}-{{ service.prefix }}-KMSKeyARN"
