services:
  app:
    build:
      context: ./mocks/app/
    ports: 
      - '5000:5000'
    networks:
      - test-net
    environment:
      - FLASK_DEBUG=true
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://127.0.0.1/status"]
      interval: 1s
      timeout: 30s
      retries: 10
      start_period: 1s

  source-db:
    image: postgres:13
    restart: always
    command: 'postgres -c log_statement=all -c fsync=off -c vm.zone_reclaim_mode=0 -c synchronous_commit=off -c checkpoint_completion_target=0.9 -c random_page_cost=1.1'
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: source
    ports:
      - '5432:5432'
    networks:
      - test-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d source -h source-db -p 5432 -U test_user | grep 'accepting connections' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  destination-db:
    image: postgres:13
    restart: always
    command: 'postgres -c log_statement=all -c fsync=off -c vm.zone_reclaim_mode=0 -c synchronous_commit=off -c checkpoint_completion_target=0.9 -c random_page_cost=1.1'
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: destination
    ports:
      - '5433:5432'
    networks:
      - test-net

  s3-mock:
    image: minio/minio
    entrypoint: sh
    command:
      - -c
      - |
        mkdir -p /data/test-dump-bucket
        touch /data/test-dump-bucket/test-dump.tar.gz
        minio server /data 
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
    networks:
      - test-net
    volumes:
      - minio_data:/data
  
  dump-task:
    build:
      context: ../images/tools/database-copy/
      dockerfile: Dockerfile
    environment:
      DATA_COPY_OPERATION: DUMP
      DB_CONNECTION_STRING: postgres://test_user:pwd@source-db:5432/source
      S3_BUCKET_NAME: s3-mock
      ECS_CLUSTER: not-sure
    depends_on:
      source-db:
          condition: service_healthy
      s3-mock:
          condition: service_started
    networks:
      - test-net

  load-task:
    build:
      context: ../images/tools/database-copy/
      dockerfile: Dockerfile
    environment:
      DATA_COPY_OPERATION: LOAD
      DB_CONNECTION_STRING: postgres://test_user:pwd@destination-db:5432/destination
      S3_BUCKET_NAME: s3-mock
      ECS_CLUSTER: not-sure
    networks:
      - test-net
    depends_on:
      - dump-task
      - destination-db
      - s3-mock

  tests:
    networks:
      - test-net
    build:
      context: .
    depends_on:
      - load-task
      - app
    environment:
      DESTINATION_DB_CONNECTION_STRING: postgres://test_user:pwd@destination-db:5432/destination
      SOURCE_DB_CONNECTION_STRING: postgres://test_user:pwd@source-db:5432/source
    volumes:
      - ./:/src

networks:
  test-net:
    driver: bridge

volumes:
  minio_data:
    driver: local
