name: Linting

on: [push]

jobs:
  lint:
    name: Run lint checks
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 #v7.0.0

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: black
        run: poetry run pre-commit run black --all-files

      - name: mixed-line-ending
        run: poetry run pre-commit run mixed-line-ending --all-files

      - name: detect-private-key
        run: poetry run pre-commit run detect-private-key --all-files

      - name: autoflake
        run: poetry run pre-commit run autoflake --all-files

      - name: docformatter
        run: poetry run pre-commit run docformatter --all-files

      - name: docs
        run: poetry run pre-commit run docs --all-files
